name: Deploy Vite site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "VITE_GOOGLE_MAPS_KEY=${{ secrets.GOOGLE_MAPS_KEY }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build Vite
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
